access_point:
  # listener on TCP or TLS
  listeners:
    - address: 0.0.0.0:8080 # listen on all interfaces

mcps:
  - id: service-1 # Unique identifier, accessible via /api/service-1/sse or /api/service-1/mcp
    upstream_id: 1
    path: /Users/fracon/Documents/code/open-source/mcp-access-point-forked/config/openapi_for_demo.yml # Local OpenAPI spec path

  # - id: service-2 # Unique identifier, accessible via /api/service-1/sse or /api/service-1/mcp
  #   upstream_id: 2
  #   path: http://localhost:8081/v3/api-docs # Local OpenAPI spec path

  - id: service-3 # Unique identifier, accessible via /api/service-1/sse or /api/service-1/mcp
    upstream_id: 3
    path: /Users/fracon/Documents/code/open-source/mcp-access-point-forked/config/simple-rest-useroperations-apidoc.yaml

upstreams: # Required upstream configuration
  - id: 1
    headers: # Headers to send to upstream service
      accept: "application/json"        # API key
      Content-Type: "application/json" # Bearer token
      api_key: "special-key"  # <-- Use this value
    nodes: # Backend nodes (IP or domain)
      "localhost:4010": 1 # Format: address:weight
  
  # - id: 2
  #   headers: # Headers to send to upstream service
  #     accept: "application/json"        # API key
  #     Content-Type: "application/json" # Bearer token
  #   nodes: # Backend nodes (IP or domain)
  #     "localhost:8081": 1 # Format: address:weight

  - id: 3
    headers: # Headers to send to upstream service
      accept: "application/json"        # API key
      Content-Type: "application/json" # Bearer token
    nodes: # Backend nodes (IP or domain)
      "localhost:4011": 1 # Format: address:weight