swagger: "2.0"
info:
  version: "1.0.0"
  title: "Simple Pet API"
  description: "A minimal Swagger 2.0 Pet API with CRUD operations."
host: "localhost:4010"
schemes:
  - http
tags:
  - name: "pet"
    description: "Operations about pets"
paths:
  /pet:
    get:
      tags:
        - "pet"
      summary: "List all pets"
      operationId: "listPets"
      produces:
        - application/json
      responses:
        200:
          description: "A list of pets."
          schema:
            type: array
            items:
              $ref: "#/definitions/Pet"
    post:
      tags:
        - "pet"
      summary: "Create a pet"
      operationId: "createPet"
      consumes:
        - application/json
      parameters:
        - in: body
          name: body
          description: Pet to add
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        201:
          description: "Pet created"
          schema:
            $ref: "#/definitions/Pet"
  /pet/{petId}:
    get:
      tags:
        - "pet"
      summary: "Get a pet by ID"
      operationId: "getPetById"
      produces:
        - application/json
      parameters:
        - name: petId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: "Pet found"
          schema:
            $ref: "#/definitions/Pet"
        404:
          description: "Pet not found"
    put:
      tags:
        - "pet"
      summary: "Update a pet by ID"
      operationId: "updatePet"
      consumes:
        - application/json
      parameters:
        - name: petId
          in: path
          required: true
          type: integer
          format: int64
        - in: body
          name: body
          description: Pet to update
          required: true
          schema:
            $ref: "#/definitions/Pet"
      responses:
        200:
          description: "Pet updated"
          schema:
            $ref: "#/definitions/Pet"
        404:
          description: "Pet not found"
    delete:
      tags:
        - "pet"
      summary: "Delete a pet by ID"
      operationId: "deletePet"
      parameters:
        - name: petId
          in: path
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: "Pet deleted"
        404:
          description: "Pet not found"
definitions:
  Pet:
    type: object
    required:
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
