access_point:
  # listener on TCP or TLS
  listeners:
    - address: 0.0.0.0:8080 # listen on all interfaces

mcps:
  - id: service-1 # Unique identifier, accessible via /api/service-1/sse or /api/service-1/mcp
    upstream_id: 1
    path: http://localhost:8081/v3/api-docs # Local OpenAPI spec path

# upstreams:
#   - id: 1
#     nodes:
#       - url: http://localhost:8081

upstreams: # Required upstream configuration
  - id: 1
    headers: # Headers to send to upstream service
      accept: "application/json"        # API key
      Content-Type: "application/json" # Bearer token
    nodes: # Backend nodes (IP or domain)
      "localhost:8081": 1 # Format: address:weight
  
