access_point:
  # listener on TCP or TLS
  listeners:
    - address: 0.0.0.0:8080 # listen on all interfaces

mcps:
  # - id: service-1 # Unique identifier, accessible via /api/service-1/sse or /api/service-1/mcp
  #   upstream_id: 1
  #   path: http://host.docker.internal:8081/v3/api-docs # Local OpenAPI spec path
  
  - id: service-2 # Unique identifier
    upstream_id: 2
    path: https://petstore.swagger.io/v2/swagger.json # Remote OpenAPI spec